9 add navigation
MarsBanana/dater-test-game pull request #10
Opened 2020-12-17 20:06 UTC by MarsBanana

Resolves #9

2020-12-18 05:24 UTC, olegwn requested changes
См коммент

2020-12-18 05:24 UTC, olegwn commented on src/pages/CreateScreen/index.tsx
> +            <Link style={customLinkStyle} href="/">
это не совсем go back, попробуй использовать стандартную навигацию F7 и сделать именно .back навигацию

2020-12-21 17:36 UTC, MarsBanana commented on src/pages/CreateScreen/index.tsx
> +            <Link style={customLinkStyle} href="/">
[фикс](https://github.com/MarsBanana/dater-test-game/pull/10/commits/3e172a12758eef0e53d51f72742998e11757a10b)

2020-12-22 03:26 UTC, olegwn approved these changes

2020-12-22 09:43 UTC, merged