13 connect to firebase
MarsBanana/dater-test-game pull request #14
Opened 2020-12-21 18:20 UTC by MarsBanana

Resolves #13

2020-12-22 03:36 UTC, olegwn commented on firestore.rules
> +          request.time < timestamp.date(2021, 1, 13);
что хотел этим сделать?)

2020-12-22 03:44 UTC, olegwn requested changes
Вот у тебя уже слишком много pull requests да еще таких которые друг с другом пересекаются, с этим надо что то делать

да и 3 открытых pull requests это максимум, у тебя уже 4
если открыто 3 - надо работать над их закрытием (меня торопить, самому что то делать), у нас такое правилое, иначе погрязнем в pull requests :)

2020-12-22 03:44 UTC, olegwn commented on src/api/index.ts
> +    db.collection("games").add({
"games" -> [magic string](https://softwareengineering.stackexchange.com/questions/365339/what-is-wrong-with-magic-strings?newreg=cba03b1e1b6c4db9bf66a9df023ac11a), лучше сразу вынести в какой то файл с константами и назвать константу описательно

2020-12-22 03:44 UTC, olegwn commented on src/firebase.ts
> +import firebase from "firebase"
вот у тебя скоро появится store.ts (наверное :) ) и firebase.ts в принципе это все конфигурация приложения, можно подумать об отдельной папке для конфигов

2020-12-22 10:36 UTC, MarsBanana commented on src/firebase.ts
> +import firebase from "firebase"
Мне кажется что конфиги для firebase стоит хранить не в файлах приложения в целом, а например в environment
А store.ts должен находиться в фолдере /store
Это же всё-таки две несвязанные логически части, так пусть и существуют раздельно :)

2020-12-22 10:47 UTC, MarsBanana commented on firestore.rules
> +          request.time < timestamp.date(2021, 1, 13);
Это дефолтный конфиг доступа в [Тестовом режиме](https://firebase.google.com/docs/firestore/quickstart?authuser=0#test-mode), при инициализации firestore права даются на месяц зачем-то :)
Можно заменить на `if true`, как в примере

2020-12-22 18:24 UTC, MarsBanana commented on src/api/index.ts
> +    db.collection("games").add({
https://github.com/MarsBanana/dater-test-game/pull/14/commits/5af2cc757264b82be7e063d46f77482977fa2a80

2020-12-23 03:57 UTC, olegwn commented on firestore.rules
> +          request.time < timestamp.date(2021, 1, 13);
понял! не видел такого еще, значит ОК

2020-12-23 03:58 UTC, olegwn commented on src/firebase.ts
> +import firebase from "firebase"
>а например в environment

а почему так считаешь? там нет секретных ключей, это не сервер,
а envoronmenets лишние заморочки/усложнения
давай обсудим)

2020-12-23 04:01 UTC, olegwn commented on src/firebase.ts
> +import firebase from "firebase"
>А store.ts должен находиться в фолдере /store

тут соглашусь

2020-12-23 10:48 UTC, MarsBanana commented on src/firebase.ts
> +import firebase from "firebase"
[Тут](https://github.com/MarsBanana/dater-test-game/pull/14/files#diff-bbb3c1ccb9e6a6964ec9c8e20bc92397186b554da6e6baf1e67fb9ede97f9bbeR3) есть apiKey, который и позволяет вести чтение/запись
В режиме тестирования доступ полностью свободный, а никаких дополнительных мер защиты не предусмотрено
В документации написано о том, что это ключ для доступа к общим данным, а для доп. защиты можно настроить, например, парольную аутентификацию
Так что на данном этапе это как бы и есть секретный ключ :)

2020-12-23 11:04 UTC, olegwn commented on src/firebase.ts
> +import firebase from "firebase"
нет) это не секретный ключ, это публичный ключ, он же при деплое клиента на хостинг попадает туда в открытом виде и в любом случае его может прочитать кто угодно, поэтому и существуют firebase security rules
эти клиентские ключи не дают полную запись/чтение ни в коем случае, только в пределах того , что позволяют security rules не более, поэтому их скрывать смысла нет

2020-12-23 11:24 UTC, MarsBanana commented on src/firebase.ts
> +import firebase from "firebase"
Ага, понял
Ну а насчет отдельной папки для конфигов, думаю пока всё находится в одном файле и не требует разделения, можно оставить как есть

2020-12-23 13:12 UTC, olegwn commented on src/firebase.ts
> +import firebase from "firebase"
это согласен, да

2020-12-23 13:12 UTC, olegwn approved these changes

2020-12-23 13:19 UTC, merged