Game page
MarsBanana/dater-test-game pull request #19
Opened 2020-12-29 12:44 UTC by MarsBanana

Resolves #4

2021-01-05 09:25 UTC, olegwn requested changes
В основном все по стилистике и читабельности.

Нужно делать упор на максимально легкое чтение кода, чтоб читалось незадумываясь.

а так все круто, продолжай!

2021-01-05 09:25 UTC, olegwn commented on src/api/playerJoin.ts
> +    const data = players.length + 1 === playersAmount ? {
снова сложная конструкция с ternary оператором

2021-01-05 09:25 UTC, olegwn commented on src/api/playerLeave.ts
> +    const newPlayers = [...players.slice(0,index), ...players.slice(index+1, players.length)]
трудно понять что здесь происходит не вдумываясь, попробуй упростить чтение/восприятие

2021-01-05 09:25 UTC, olegwn commented on src/pages/CreateScreen/CreateGameForm.tsx
> +            f7.views.main.router.navigate("/game/")
не думал, что навигацию лучше в саги вынести? ведь по идее после dispatch(createGame) и только после успешного создания игры надо перебрасывать на экран игр, а если не успешно - что то выводить пользователю, алерт/еще что то там

2021-01-05 09:25 UTC, olegwn commented on src/pages/GameScreen/GameInfo.tsx
> +        <CenteredText title text={data.gameName} />
упрости компонент, вынеси разные логические блоки в описательные функции или миникомпоненты в этом же файле

например

{gameNotStartedYet()}
{gameHasStarted()}

и проч

2021-01-05 09:25 UTC, olegwn commented on src/pages/GameScreen/Winner.tsx
> +                text={`${winner?.name} won with ${winner?.points} point${
лучше вычисления вынести в переменную, проще будет читаться код

2021-01-05 09:25 UTC, olegwn commented on src/pages/GameScreen/index.tsx
> +    const data = useSelector<IState, GameData | null>((state) => state.currentGame)
странное название для переменной data
а почему не currentGame ? 
ну или что то по лучше, чем data))

2021-01-05 09:25 UTC, olegwn commented on src/pages/GameScreen/index.tsx
> +                {!data?.isStarted && <GoBack />}
вот здесь хорошо видно, чем название переменной data плохо, приходится помнить постоянно что оно значит

2021-01-05 09:25 UTC, olegwn commented on src/pages/GameScreen/index.tsx
> +    const id = useSelector<IState, string | undefined>((state) => state.currentId)
id - что за id? чтобы понять - надо думать

2021-01-05 09:25 UTC, olegwn commented on src/store/sagas.ts
> +        const id = yield api.createGame(action.payload)
во, снова возвращаясь к этому id, там где я писал , что он возвращает Promise
ты как раз этот Promise и резолвишь через yield

поэтому в функции createGame переменную id лучше было бы назвать idPromise а еще лучше типизировать, чтобы было ясно, что возвращается Promise, мелочь, но каждая мелочь важна

2021-01-05 09:25 UTC, olegwn commented on src/store/sagas.ts
> +        yield call(api.playerJoin,{name,id,players,playersAmount})
кстати, раз у тебя нет тестов, то можно в коде везде и без call обойтись, это так, к сведению)

2021-01-05 09:25 UTC, olegwn commented on src/store/sagas.ts
> +        const id = yield select((state) => state.currentId)
я бы на твоем месте не менял название переменной, currentId и все, а еще лучше, это описательное название, currentGameId 
не надо бояться длинных переменных, читабельность всегда в приоритете

2021-01-05 13:36 UTC, MarsBanana commented on src/api/createGame.ts
> +        .then(() => remoteConfig.getNumber(configConstants.ROUNDS))
Это же указано в доке с описанием задания)

2021-01-05 13:36 UTC, MarsBanana commented on src/api/createGame.ts
> +    const id = remoteConfig
Да, но потом резолвится в сагах

2021-01-05 14:15 UTC, MarsBanana commented on src/store/sagas.ts
> +        const id = yield select((state) => state.currentId)
Оставил currentGameId

2021-01-05 14:47 UTC, olegwn requested changes
см комменты

2021-01-05 14:47 UTC, olegwn commented on src/pages/GameScreen/GameInfo.tsx
> +            />
а это чего не разбил?

2021-01-05 14:47 UTC, olegwn commented on src/pages/GameScreen/index.tsx
> +                {!currentGame?.isStarted && <GoBack />}
вот уже гораздо лучше читается, прямо как обычный текст

2021-01-05 14:47 UTC, olegwn commented on src/pages/GameScreen/index.tsx
> +    const name = useSelector<IState, string | null>((state) => state.name)
вопрос, это имя игрока или имя игры? должно быть без вопросов по коду понятно

2021-01-05 14:47 UTC, olegwn commented on src/components/Loader.tsx
> +    <div style={{maxWidth: "32px", marginLeft: "calc(50% - 16px)"}}>
у тебя стили то в переменной то inline, лучше делать однообразно

2021-01-05 14:47 UTC, olegwn commented on src/api/createGame.ts
> +        .then(() => remoteConfig.getNumber(configConstants.ROUNDS))
я и забыл))

2021-01-05 14:47 UTC, olegwn commented on src/pages/JoinScreen/GamesList.tsx
> +        f7.views.main.router.navigate("/game/")
ты таки реши, в сагах ты делаешь навигацию, или в компонентах)

2021-01-05 14:47 UTC, olegwn commented on src/store/reducer.ts
> +    currentGame: null,
почему кстати здесь нет
 currentGameId?: string
?

2021-01-05 14:47 UTC, olegwn commented on src/store/sagas.ts
> +      const action = yield take(updateGameChannel)
пока не понял, где ты пишешь в updateGameChannel ? 
так понимаю еще не реализовано?

2021-01-05 14:47 UTC, olegwn commented on src/store/sagas.ts
> +        const currentGameId = yield select((state) => state.currentGameId)
у меня еще такой вопрос: а почему ты id игры не хранишь внутри currentGame
с именем игры тоже самое

2021-01-05 14:52 UTC, MarsBanana commented on src/pages/GameScreen/GameInfo.tsx
> +            />
По сравнению с остальными блоками, этот выглядит понятнее, но раз ты обратил внимание, тоже вынесу

2021-01-05 14:52 UTC, MarsBanana commented on src/pages/GameScreen/index.tsx
> +    const name = useSelector<IState, string | null>((state) => state.name)
Имя игрока, переименую в playerName

2021-01-05 22:03 UTC, MarsBanana commented on src/pages/JoinScreen/GamesList.tsx
> +        f7.views.main.router.navigate("/game/")
Перенес в саги

2021-01-05 22:05 UTC, MarsBanana commented on src/store/reducer.ts
> +    currentGame: null,
При инициализации currentGameId = undefined, потому что у нас его просто нет
Значение присваивается при создании игры, или присоединении к существующей игре
После выхода из игры сбрасывается

2021-01-05 22:05 UTC, MarsBanana commented on src/store/sagas.ts
> +      const action = yield take(updateGameChannel)
Это лишний код, уберу

2021-01-05 22:09 UTC, MarsBanana commented on src/store/sagas.ts
> +        const currentGameId = yield select((state) => state.currentGameId)
Имя игры хранится внутри currentGame
А про currentGameId, по-моему из-за степени важности этой переменной она должна находится отдельно
Она у нас есть до того, как появляется currentGame

2021-01-06 07:29 UTC, olegwn commented on src/components/Loader.tsx
> +    <div style={{maxWidth: "32px", marginLeft: "calc(50% - 16px)"}}>
так что в итоге?)

2021-01-06 07:34 UTC, olegwn reviewed
Пару комментов, они на твое усмотрение, можешь заканчивать этот pull/сливать

2021-01-06 07:34 UTC, olegwn commented on src/store/reducer.ts
> +    currentGame: null,
ну ок, я бы сделал currentGameId: null 
для явности

2021-01-06 07:34 UTC, olegwn commented on src/components/Loader.tsx
> +    <div style={{maxWidth: "32px", marginLeft: "calc(50% - 16px)"}}>
так что в итоге?)

2021-01-06 23:19 UTC, MarsBanana commented on src/components/Loader.tsx
> +    <div style={{maxWidth: "32px", marginLeft: "calc(50% - 16px)"}}>
вынес в переменные

2021-01-06 23:52 UTC, merged